language: android
jdk: oraclejdk8

sudo: true

android:
  components:

    - platform-tools
    - tools

    # The BuildTools version
    - build-tools-25.0.2

    # The SDK version
    - android-26

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25

    - sys-img-armeabi-v7a-android-23

  licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
        - ".+"

before_script:
  - echo no | android create avd --force --name test --target android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
